pin_scene/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('pinscene.urls', namespace='pinscene')),
]

pinscene/urls.py
"""Define URL pattern for pinscene app"""

from django.conf.urls import url

from . import views

urlpatterns = [

    #Home page for Pinscene app
    url(r'^$', views.index, name='index'),
    #Show all pins
    url(r'^pins/$', views.pins, name='pins'),
    #Detail page for single pinball machine
    url(r'^pins/(?P<pin_id>\d+)/$', views.pin, name='pin'),
    #page for adding a new pin
    url(r'^new_pin/$', views.new_pin, name='new_pin'),
    #page for editing existing pins
    url(r'^edit_pin/(?P<pin_id>\d+)/$', views.edit_pin, name="edit_pin"),
    #delete a pin
     url(r'^delete/(?P<pk>[0-9]+)/$', views.delete_pin, name='delete_pin')
]

users/urls.py
"""Defines URL patters for users"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    #login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    ]       

pinscene/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Location(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    address = models.CharField(max_length=200)
    notes = models.TextField(default='blank')

    def __str__(self):
        return self.name

class Pin(models.Model):
    """A Pin represents an individual pinball machine"""
    title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=360)
    year = models.IntegerField()
    designer = models.CharField(max_length=200)
    played = models.BooleanField(default=False)
    note = models.TextField()

    def __str__(self):
        """Return string representation of the model"""
        return self.title

users/models.py
from django.db import models

# Create your models here.

pinscene/forms.py
from django import forms

from django import forms
from .models import Pin, Location


class PinForm(forms.ModelForm):
    class Meta:
        model = Pin
        fields = ['title', 'location', 'year', 'designer', 'note', 'played']
        labels = {'title': 'title'}

class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ['name', 'address', 'notes']

pinscene/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Pin, Location
from .forms import PinForm, LocationForm
# Views for PinScene

def index(request):
    """Homepage for pinscene app"""
    return render(request, 'pinscene/index.html')

def pins(request):
    """Show all pins"""
    pins = Pin.objects.order_by('-date_added') #get list of all pins in db
    context = {'pins': pins}
    return render(request, 'pinscene/pins.html', context) #render list of pins

def pin(request, pin_id):
    """shows single pinball machine and its information"""
    pin = Pin.objects.get(id=pin_id) #get particular pin by id.
    context = {'pin': pin}
    return render(request, 'pinscene/pin.html', context)

@login_required
def new_pin(request):
    """Add a new pinball machine to database"""
    if request.method != 'POST':
        #No data submitted -- create blank form
        form = PinForm()
    else:
        #POST data submitted -- process data.
        form = PinForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('pinscene:pins'))

    context = {'form': form}
    return render(request, 'pinscene/new_pin.html', context)

@login_required #prevent non-registered users from editing pins
def edit_pin(request, pin_id):
    """edit an existing pin"""
    pin = Pin.objects.get(id=pin_id)

    if request.method != 'POST':
        form = PinForm(instance=pin)
    else:
        form = PinForm(instance=pin, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('pinscene:pin', args=[pin.id]))
    
    context = {'pin':pin, 'form':form}
    return render(request, 'pinscene/edit_pin.html', context)
@login_required
def delete_pin(request, pk):
    pin = get_object_or_404(Pin, pk=pk)  # Get your current cat

    if request.method == 'POST':         # If method is POST,
        pin.delete()                     # delete the cat.
        return redirect('pinscene:pins')             # Finally, redirect to the homepage.

    return render(request, 'pinscene:pins', {'pin': pin})

users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """logs the user out"""
    logout(request)
    return HttpResponseRedirect(reverse('pinscene:index'))

def register(request):
    """registers a new user"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        #process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #logs user in and directs to home page
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('pinscene:index'))
        
    context = {'form': form}
    return render(request, 'users/register.html', context)

pinscene/templates/pinscene/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv"X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>PinScene</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>
    
    <body>

        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                    <a class="navbar-brand" href="{% url 'pinscene:index' %}">
                        PinScene</a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'pinscene:pins' %}">Pins</a></li>
                    </ul>

                    <ul class="nav navbar navbar-right">
                      {% if user.is_authenticated %}
                        <li><a>Hello, {{user.username }}</a></li>
                        <li><a href="{% url 'users:logout' %}">Logout</a></li>
                      {% else %}
                        <li><a href="{% url 'users:register' %}">Register</a></li> 
                        <li><a href="{% url 'users:login' %}">Login</a></li>
                      {% endif %}
                    </ul>
                </div>



            </div>
        </nav> 

        <div class="container">

            <div class="page-header">
                {% block header %} {% endblock header %}
            </div>
            <div>
                {% block content %} {% endblock content %}
            </div>

        </div>
    </body>
</html>

pinscene/templates/pinscene/delete_pin.html
<form action="{% url 'pins:delete_pin' pin.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete pin">
</form>

pinscene/templates/pinscene/edit_pin.html
{% extends "pinscene/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Edit Pin:</h2>
{% endblock header %}

{% block content %}

  <p><a href="{% url 'pinscene:pin' pin.id %}">{{ pin }}</a></p>

  <p>Edit Pin:</p>

  <form action="{% url 'pinscene:edit_pin' pin.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button name="submit">Save Changes</button>      
  </form> 

{% endblock content %}

pinscene/templates/pinscene/index.html
{% extends "pinscene/base.html" %}

{% block header %}
  <div class='jumbotron'>
      <h1>Find Pinball Machines and Pinball enthusiasts in your area!</h1>
  </div>
{% endblock header %}


{% block content %}
  <h2>Pinscene is an app that helps you find new pinball machines in your town. You can also keep track of machines you're already aware of and connect with other players. More features to come! Click on Pins to get started! </h2>
{% endblock content %}

pinscene/templates/pinscene/new_pin.html
{% extends "pinscene/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add A New Pin:</h2>
{% endblock header %}

{% block content %}
  
  <form action="{% url 'pinscene:new_pin' %}" method='post'>
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-priary">Add Pin</button>
      {% endbuttons %}
  </form>

{% endblock content %}

pinscene/templates/pinscene/pin.html
{% extends 'pinscene/base.html' %}

{% block header %}
  <h2>{{ pin }}</h2>
{% endblock header %}

{% block content %}

<div class = "panel panel-default">
    <div class="panel-heading">
        <h3>
            {{ pin.title }}
            <small>
                <a href="{% url 'pinscene:edit_pin' pin.id %}">edit pin</a>
            </small>
        </h3>
    </div>
    <div class="panel-body">
        <p>Designer: {{ pin.designer }}</p>
        <p>Location: {{ pin.location }}</p>
        <p>Played: {{ pin.played }}</p>   
        <h2>Notes:</h2> 
        {{ pin.note|linebreaks }}     
    </div>
</div>

<a href="{%url 'pinscene:pins' %}"><button name="submit">Back To Pin List</button></a>
<form action="{% url 'pinscene:delete_pin' pin.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete pin">
</form>




{% endblock %}

pinscene/templates/pinscene/pins.html
{% extends "pinscene/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h1>Pins</h1>
{% endblock header %}

{% block content %}
  <ul>
      {% for pin in pins %}
        <li>
            <h3>
                <a href="{% url 'pinscene:pin' pin.id %}">{{ pin }}</a>
            </h3>
        </li>
      {% empty %}
        <li>No pins have been added yet.</li>
      {% endfor %}    
  </ul>
  
 <h3> <a href="{% url 'pinscene:new_pin' %}"><button name="submit">Add New Pin</button></a> </h3>
   

{% endblock content %}

users/templates/users/login.html
{% extends 'pinscene/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log In To PinScene.</h2>
{% endblock header %}

{% block content %}


  <form method="post" action="{% url 'users:login' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
      <button name="submit">Log In</button>
      {% endbuttons %}

      <input type="hidden" name="next" value="{% url 'pinscene:index' %}" />
  </form>

{% endblock content %}
  

users/templates/users/register.html
{% extends "pinscene/base.html" %}
{% load bootstrap3 %}
{% block content %}


<h1>Welcome to PinScene. Let's Get Started</h1>
<form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit">Register</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'pinscene:index' %}" />
</form>

{% endblock content %}